name: OSV-Scanner PR Scan

permissions:
  contents: read
  security-events: write
  id-token: write
  issues: write
  # pull-requests: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
    inputs:
      scan-args:
        description: "Custom osv-scanner arguments (See https://google.github.io/osv-scanner/usage/ for options, you cannot set --format or --output)"
        type: string
      results-file-name:
        description: "File name of the result SARIF file"
        type: string
        default: results.sarif

jobs:
  scan-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Run checkout"
        uses: actions/checkout@v4

      - name: "Run scanner on new code"
        uses: google/osv-scanner/actions/scanner@main
        with:
          scan-args: |-
            ${{ inputs.results-file-name }}