name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: '12 12 * * 1'
 # Change "main" to your default branch if you use a different name, i.e. "master"
  push:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

jobs:

  extract-deps:
    name: Extract Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: "upload osv-scanner deps" # Upload the deps
        uses: actions/upload-artifact@v3
        with:
          name: converted-OSV-Scanner-deps
          path: osv-scanner-deps.json
          retention-days: 2
  vuln-scan:
    name: Vulnerability scanning
    # makes sure the extraction step is completed before running the scanner
    needs:
      extract-deps
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable.yml@main"
    with:
      # Download the artifact uploaded in extract-deps step
      download-artifact: converted-OSV-Scanner-deps
      # Scan only the file inside the uploaded artifact
      scan-args: |-
        --lockfile=osv-scanner:osv-scanner-deps.json
    permissions:
      # Needed to upload the SARIF results to code-scanning dashboard.
      security-events: write
      contents: read