name: OSV-Scanner PR scanning reusable

permissions:
  contents: read
  security-events: write
  issues: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
 
jobs:
  scan-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout target branch"
        uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-pr.yml@main"
        with:
          # Only scan the top level go.mod file without recursively scanning directories since
          # this is pipeline is about releasing the go module and binary
          scan-args: |-
            --skip-git
            ./
    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
