name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: '12 12 * * 1'
 # Change "main" to your default branch if you use a different name, i.e. "master"
  push:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

permissions:
    contents: read # to fetch code (actions/checkout)
      
jobs:

 
  vuln-scan:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable.yml@main"
    with:
      # Only scan the top level go.mod file without recursively scanning directories since
      # this is pipeline is about releasing the go module and binary
      scan-args: |-
        --skip-git
        ./
    
    permissions:
      # Needed to upload the SARIF results to code-scanning dashboard.
      security-events: write
      contents: write              # This is required for actions/checkout@v1