name: OSV-Scanner PR scanning reusable

permissions:
  contents: read
  security-events: write
 
on:
  push:
    branches: [ master ]

  workflow_dispatch:

  workflow_call:
    inputs:
      scan-args:
        description: "Custom osv-scanner arguments (See https://google.github.io/osv-scanner/usage/ for options, you cannot set --format or --output)"
        type: string
        default: |-
          -r --skip-git
      results-file-name:
        description: "File name of the result SARIF file"
        type: string
        default: results.sarif
 
jobs:
  scan-pr:
    runs-on: ubuntu-latest
    steps:
      # check out
      - uses: actions/checkout@v3
      
      - name: "Run scanner on main branch"
        uses: google/osv-scanner/actions/scanner@master
        with:
          scan-args: |-
            --format=json --output=new-results.json
        continue-on-error: false

    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      issues: write
